/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],

  safelist: [
    "text-primary",
    "text-secondary",
    "text-danger",
    "text-black",
    "text-white",
    "bg-primary",
    "bg-secondary",
    "bg-danger",
    "bg-black",
    "bg-darkGray",
    "bg-white",
    "text-lightPrimary",
    "text-darkPrimary",
    "text-lightSecondary",
    "text-darkSecondary",
    "text-lightTertiary",
    "text-darkTertiary",
    "text-lightBlack",
    "text-darkBlack",
    "text-lightDarkGray",
    "text-darkerDarkGray",
    "text-lightGray",
    "text-darkerGray",
    "text-lighterGray",
    "text-darkLightGray",
    "text-lightDanger",
    "text-darkDanger",
    "text-lightWarning",
    "text-darkWarning",
    "text-lightBronze",
    "text-darkBronze",
    "text-darkDarkBronze",
    "bg-black",
    "bg-lightPrimary",
    "bg-darkPrimary",
    "bg-lightSecondary",
    "bg-darkSecondary",
    "bg-lightTertiary",
    "bg-darkTertiary",
    "bg-lightBlack",
    "bg-darkBlack",
    "bg-lightDarkGray",
    "bg-darkerDarkGray",
    "bg-lightGray",
    "bg-darkerGray",
    "bg-lighterGray",
    "bg-darkLightGray",
    "bg-lightDanger",
    "bg-darkDanger",
    "bg-lightWarning",
    "bg-darkWarning",
    "bg-lightBronze",
    "bg-darkBronze",
    "bg-darkDarkBronze",
    "hover:bg-tertiary",
    "hover:bg-primary",
    "hover:bg-secondary",
    "hover:bg-danger",
    "hover:bg-black",
    "hover:bg-darkGray",
    "hover:bg-white",
    "hover:bg-lightPrimary",
    "hover:bg-darkPrimary",
    "hover:bg-lightSecondary",
    "hover:bg-darkSecondary",
    "hover:bg-lightTertiary",
    "hover:bg-darkTertiary",
    "hover:bg-lightBlack",
    "hover:bg-darkBlack",
    "hover:bg-lightDarkGray",
    "hover:bg-darkerDarkGray",
    "hover:bg-lightGray",
    "hover:bg-darkerGray",
    "hover:bg-lighterGray",
    "hover:bg-darkLightGray",
    "hover:bg-lightDanger",
    "hover:bg-darkDanger",
    "hover:bg-lightWarning",
    "hover:bg-darkWarning",
    "hover:bg-lightBronze",
    "hover:bg-darkBronze",
    "hover:bg-darkDarkBronze",
    "hover:text-primary",
    "hover:text-secondary",
    "hover:text-danger",
    "hover:text-black",
    "hover:text-white",
    "hover:text-lightPrimary",
    "hover:text-darkPrimary",
    "hover:text-lightSecondary",
    "hover:text-darkSecondary",
    "hover:text-lightTertiary",
    "hover:text-darkTertiary",
    "hover:text-lightBlack",
    "hover:text-darkBlack",
    "hover:text-lightDarkGray",
    "hover:text-darkerDarkGray",
    "hover:text-lightGray",
    "hover:text-darkerGray",
    "hover:text-lighterGray",
    "hover:text-darkLightGray",
    "hover:text-lightDanger",
    "hover:text-darkDanger",
    "hover:text-lightWarning",
    "hover:text-darkWarning",
    "hover:text-lightBronze",
    "hover:text-darkBronze",
    "hover:text-darkDarkBronze",
    "hover:my-1",
    "hover:mx-2",
    "hover:py-[2px]",
    "hover:px-[0px]",
    "place-content-center",
    "align-middle",
    "content-center",
    "leading-100",
    "grow",
    "w-auto",
    "w-full",
    "w-80",
    "w-64",
    "w-56",
    "w-32",
    "w-28",
    "w-20",
    "w-16",
    "w-14",
    "w-12",
    "w-10",
    "w-7",
    "w-5",
    "w-4",
    "w-3",
    "w-3/4",
    "h-32",
    "h-24",
    "h-20",
    "h-14",
    "h-12",
    "h-10",
    "h-8",
    "h-7",
    "h-5",
    "h-4",
    "h-3",
    "pr-3",
    "pr-2",
    "pl-1",
    "py-5",
    "w-[768px]",
    "w-[480px]",
    "w-[393px]",
    "w-[385px]",
    "w-[300px]",
    "w-[260px]",
    "w-[224px]",
    "w-[220px]",
    "w-[200px]",
    "w-[191px]",
    "w-[182px]",
    "w-[150px]",
    "w-[135px]",
    "w-[132px]",
    "w-[126px]",
    "w-[115px]",
    "w-[112px]",
    "w-[108px]",
    "w-[90px]",
    "w-[88px]",
    "w-[80px]",
    "w-[72px]",
    "w-[53px]",
    "w-[18px]",
    "w-[14px]",
    "w-[10px]",
    "h-[740px]",
    "h-[739px]",
    "h-[638px]",
    "h-[490px]",
    "h-[476px]",
    "h-[422px]",
    "h-[380px]",
    "h-[334px]",
    "h-[330px]",
    "h-[316px]",
    "h-[86px]",
    "h-[72px]",
    "h-[68px]",
    "h-[46px]",
    "h-[38px]",
    "h-[35px]",
    "h-[30px]",
    "h-[18px]",
    "h-[14px]",
    "h-[10px]",
    "h-[1px]",
    "h-full",
    "h-9",
    "px-[30px]",
    "p-[10px]",
    "p-[6px]",
    "p-[3px]",
    "p-[2px]",
    "pt-[10px]",
    "pt-[1px]",
    "pb-[11px]",
    "pb-[6px]",
    "pb-2",
    "pb-1",
    "py-[9px]",
    "py-[6px]",
    "py-[3px]",
    "py-[2px]",
    "px-[51px]",
    "px-[6px]",
    "px-5",
    "pt-4",
    "mx-[2px]",
    "max-w-xs",
    "max-w-[480px]",
    "max-w-[260px]",
    "max-w-64",
    "max-w-28",
    "min-w-[260px]",
    "min-w-[200px]",
    "min-w-[100px]",
    "min-w-28",
    "min-w-12",
    "min-w-10",
    "min-w-6",
    "max-h-20",
    "min-h-10",
    "min-h-6",
    "inline-flex",
    "flex-shrink-0",
    "flex-grow",
    "flex-row-reverse",
    "bottom-full",
    "top-full",
    "top-[1px]",
    "top-[2px]",
    "top-[3px]",
    "right-full",
    "left-full",
    "rotate-90",
    "-rotate-90",
    "translate-x-4",
    "translate-x-3",
    "translate-x-3.5",
    "translate-x-2",
    "translate-x-1",
    "translate-x-0.5",
    "translate-x-2/3",
    "translate-x-1/2",
    "translate-y-1/2",
    "-translate-x-1/2",
    "-translate-y-1/2",
    "translate-x-full",
    "translate-y-0",
    "translate-y-full",
    "transform",
    "transition-all",
    "transition-height",
    "transition-transform",
    "mt-4",
    "m-1",
    "my-[2px]",
    "mx-1",
    "mx-3",
    "mx-4",
    "mx-8",
    "-mx-2",
    "mr-1",
    "mr-3",
    "m-0.5",
    "mb-1",
    "mt-[6px]",
    "-mt-0.5",
    "-mb-0.5",
    "-ml-0.5",
    "-mr-0.5",
    "-ml-1.5",
    "-mr-1.5",
    "leading-7",
    "leading-5",
    "leading-4",
    "whitespace-normal",
    "border-transparent",
    "border-b",
    "border-t-0",
    "border-b-0",
    "border-b-lg",
    "border-t-lg",
    "border-y-0",
    "break-words",
    "transition-max-height",
    "bg-gradient-to-br",
    "from-darkGray to-tertiary",
    "from-darkGray",
    "from-iron",
    "from-bronze",
    "from-silver",
    "from-warning",
    "from-primary",
    "to-tertiary",
    "rounded",
    "rounded-sm",
    "rounded-md",
    "rounded-lg",
    "rounded-t-lg",
    "rounded-b-lg",
    "opacity-20",
    "opacity-10",
    "top-1",
    "right-4",
    "right-1",
    "right-0",
    "left-4",
    "left-0",
    "-right-4",
    "inset-y-0",
    "right-[-14px]",
    "justify-center",
    "origin-top-right",
    "gap-l-3",
    "gap-r-2",
    "gap-[6px]",
    "gap-[5px]",
    "gap-[3px]",
    "gap-[2px]",
    "gap-5",
    "fill-primary",
    "text-[32px]",
    "text-[18px]",
    "text-[10px]",
    "text-center",
    "border-b-[1px]",
    "blur-sm",
    "shadow-inherit",
    "shadow-primary",
    "shadow-danger",
    "shadow-darkGray",
    "shadow-sm",
    "rounded-l",
    "rounded-r",
    "grid",
    "grid-cols-2",
    "items-end",
    "z-50",
    "z-10",
    "break-normal",
    "break-words",
    "break-all",
    "self-center",
    "md:w-[480px]",
    "md:w-[182px]",
    "md:w-12",
    "md:h-[638px]",
    "md:h-[262px]",
    "md:h-10",
    "md:flex-row",
    "md:text-center",
    "md:table-cell",
    "md:w-1/3",
    "md:w-auto",
    "md:flex-col-reverse",
    "md:flex-row-reverse",
    "md:flex-col",
    "md:flex-row",
    "md:right-0",
    "md:left-auto",
    "md:font-medium",
    "text-7xl",
    "hidden",
    "md:flex",
    "md:hidden",
    "md:block",
    "md:text-sm",
    "sm:flex-row",
    "sm:w-1/2",
    "sm:gap-0",
    "sm:w-12",
    "overflow-x-scroll",
    "zf:h-8",
    "zf:text-sm",
    "zf:text-xs",
    "zf:font-medium",
    "zf:text-xl",
    "zf:flex-row",
    "zf:w-[220px]",
    "zf:items-center",
    "zf:content-center",
    "zf:p-[10px]",
    "zf:w-5",
    "zf:h-5",
    "duration-300",
    "pl-8",
    "md:w-full",
    "md:h-full",
    "w-3/4",
    "h-3/4",
    "sm:text-sm",
    "sm:font-medium",
    "sm:gap-4",
    "top-1/4",
    "top-8",
    "sm:top-8",
    "top-[26px]",
    "md:px-16",
    "md:py-6",
    "truncate",
    "max-w-xs",
    "pt-1",
    "border-lightDanger",
    "border-darkDanger",
    "border-secondary",
    "text-lightDanger",
    "bg-darkDanger",
    "gap-8",
    "border-phthalo",
    "space-x-0",
    "-ml-4",
    "hover:space-x-1",
    "first:ml-0",
    "group-hover:ml-0",
    "bg-gradient-to-r",
    "group-hover:block",
    "group-hover",
    "group-hover:opacity-100",
    "leading-normal",
    "md:text-base",
    "md:text-sm",
    "md:gap-2",
    "md:gap-4",
    "border-darkPrimary",
    "hover:border-brightDanger",
    "hover:text-brightDanger",
    "hover:text-brightPrimary",
    "hover:shadow-primary",
    "hover:shadow-danger",
    "hover:border-primary",
    "hover:text-primary",
    "hover:shadow-primary",
    "md:w-8",
    "md:h-8",
    "md:w-16",
    "md:h-16",
    "text-4xl",
    "rounded-t-lg",
    "md:rounded-l-full",
    "md:border-r-0",
    "md:rounded-r-full ",
    "rounded-l-full",
    "rounded-t-none",
    "rounded-l-lg",
    "md:rounded-t-lg",
    "md:rounded-none",
    "md:rounded-b-lg",
    "rounded-r-lg",
    "w-16",
    "min-w-16",
    "min-h-16",
    "md:p-0",
    "md:min-w-16",
    "md:min-h-16",
    "w-26",
    "h-26",
    "mt-7",
    "ml-5",
    "text-glow",
    "mb-20",
    "-z-10",
    "z-30",
    "w-full",
    "overflow-x-hidden",
    "overflow-hidden",
    "max-w-full",
    "backdrop-blur-sm",
    "opacity-75",
    "opacity-25",
    "bg-tertiary/75",
    "hover:bg-primary/15",
    "grid",
    "group-hover:text-white",
    "md:grid",
    "grid-rows-2",
    "grid-cols-3",
    "col-start-2",
    "col-span-2",
    "col-start-1",
    "row-start-1",
    "grid-cols-[1fr, 2fr, 1fr]",
    "grid-cols-[minmax(0,1fr),minmax(0,2fr),minmax(0,1fr)]",
    "w-[450px]",
    "min-w-[450px]",
    "min-h-52",
    "lg:grid",
    "bg-gradient-to-br",
    "from-tertiary/75",
    "to-darkTertiary/75",
    "from-dawnTertiary/75",
    "from-darkGray/75",
    "bg-gradient-to-l",
    "bg-[length:400%_100%]",
    "bg-[0%_0%]",
    "bg-[50%_0%]",
    "bg-[100%_0%]",
    "lg:container",
    "lg:mx-auto",
    "xl:max-w-[1024px]",
    "via-dawnTertiary/75",
    "md:row-start-2",
    "md:col-start-2",
    "row-start-3",
    "col-start-2",
    "md:hidden",
    "from-45%",
    "via-10%",
    "to-45%",
    "bg-bottom",
    "bg-cover",
    "object-contain",
    "top-[100px]",
    "h-10/12",

    "before:absolute",
    "before:inset-[-2px]",
    "before:rounded-full",
    "before:bg-primary/10",
    "before:animate-pulse-glow",
    "before:blur-[2px]",
    "before:-z-10",
    "after:absolute",
    "after:inset-[-1px]",
    "after:rounded-full",
    "after:bg-gradient-to-r",
    "after:from-primary/20",
    "after:to-transparent",
    "after:animate-pulse-slow",
    "after:blur-[1px]",
    "after:-z-10",
    "bg-white",
    "bg-opacity-5",
    "bg-opacity-10",
    "bg-gradient-to-r",
    "from-purple-500",
    "to-blue-500",
    "rounded-full",
    "rounded-3xl",
    "backdrop-blur-lg",
    "shadow-xl",
    "shadow-purple-500/20",
    "border-opacity-20",
    "hover:shadow-purple-500/30",
    "transition-all",
    "duration-300",
    "ease-in-out",
    "text-gray-600",
    "bg-gradient-to-br",
    "appearance-auto",
    "hover:futarchyBurgundy/50",
    "hover:futarchyBurgundy",
    "hover:fill-white",
    "z-20",
    "z-40",
    "z-50",
    "translate-y-48",

    "y-1/2",
    "grid-rows-[auto_min-content_auto]",

    // Statistical display
    "text-6xl",
    "text-5xl",
    "font-light",
    "tracking-tight",

    // Layout utilities
    "grid-cols-1",
    "md:grid-cols-2",
    "lg:grid-cols-3",
    "gap-8",
    "space-y-4",

    // Decorative elements
    "rotate-6",
    "-rotate-6",
    "scale-95",
    "hover:scale-100",
  ],

  theme: {
    screens: {
      zf: "864px",
      xl: "1280px",
      lg: "1024px",
      md: "768px",
      sm: "640px",
      pc: "900px",
    },
    extend: {
      keyframes: {
        "slide-down": {
          "0%": { opacity: 0, transform: "translateY(-20px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        "slide-up": {
          "0%": { opacity: 1, transform: "translateY(0)" },
          "100%": { opacity: 0, transform: "translateY(-20px)" },
        },
        "subtle-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.8" },
        },
        "ping-once": {
          "0%": { transform: "scale(1)", opacity: "1" },
          "75%, 100%": { transform: "scale(2)", opacity: "0" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: 0.1 },
          "50%": { opacity: 0.3 },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-20px)" },
        },
        "gradient-float": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-20px)" },
        },
        rotate: {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        pulse: {
          "0%, 100%": { transform: "scale(1)", opacity: "0.5" },
          "50%": { transform: "scale(1.1)", opacity: "0.8" },
        },
        'slide-in': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' }
        },
        'pulse-blue': {
          '0%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(0, 144, 255, 0.4)' },
          '70%': { transform: 'scale(1)', boxShadow: '0 0 0 6px rgba(0, 144, 255, 0)' },
          '100%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(0, 144, 255, 0)' }
        },
        'pulse-gold': {
          '0%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(245, 196, 0, 0.4)' },
          '70%': { transform: 'scale(1)', boxShadow: '0 0 0 6px rgba(245, 196, 0, 0)' },
          '100%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(245, 196, 0, 0)' }
        },
        'subtle-pulse': {
          '50%': {
            opacity: '.75',
          },
        },
      },
      animation: {
        "slide-down": "slide-down 0.1s ease-out forwards",
        "slide-up": "slide-up 0.1s ease-out forwards",
        "subtle-pulse": "subtle-pulse 2s ease-in-out infinite",
        "ping-once": "ping-once 1s cubic-bezier(0, 0, 0.2, 1) forwards",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "pulse-glow": "pulse-glow 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "float": "float 6s ease-in-out infinite",
        "gradient-float": "gradient-float 15s ease infinite",
        "float-slow": "float 8s ease-in-out infinite",
        "rotate-slow": "rotate 12s linear infinite",
        "pulse-slow": "pulse 6s ease-in-out infinite",
        'slide-in': 'slide-in 0.3s ease-out',
        'pulse-blue': 'pulse-blue 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-gold': 'pulse-gold 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'subtle-pulse': 'subtle-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      width: {
        22: "88px",
        87: "348px",
        90: "360px",
        100: "400px",
        120: "480px",
        143: "572px",
        220: "880px",
      },

      height: {
        12: "48px",
        87: "348px",
        100: "400px",
        107: "428px",
        133: "532px",
        142: "568px",
        147: "588px",
      },
      backdropBlur: {
        xs: '2px',
      },
      colors: {
        primary: "#45FFC5",
        lightPrimary: "#73FFD3",
        shadePrimary: "#34bf94",
        darkPrimary: "#2d9173",
        brightPrimary: "#a4ffe2",
        secondary: "#0B3F42",
        lightSecondary: "#486F71",
        darkSecondary: "#0f2d2f",
        tertiary: "#1C2322",
        dawnTertiary: "#292D2D",
        lightTertiary: "#545A59",
        darkTertiary: "#181f1e",
        black: "#141A1A",
        lightBlack: "#4E5353",
        darkBlack: "#141A1A",
        darkGray: "#31403C",
        lightDarkGray: "#414F4B",
        darkerDarkGray: "#2D3B37",
        gray: "#6D8C8E",
        lightGray: "#FAFAFA",
        darkerGray: "#425556",
        lighterGray: "#EEFFF8",
        darkLightGray: "#556465",
        danger: "#F0525C",
        lightDanger: "#F37D84",
        brightDanger: "#f7aaaf",
        darkDanger: "#86373c",
        deepDanger: "#521414",
        warning: "#E3BB42",
        lightWarning: "#EACC71",
        darkWarning: "#806e2f",
        bronze: "#DBC0A5",
        lightBronze: "#E4CFBB",
        darkBronze: "#7b7062",
        darkDarkBronze: "#554939",
        iron: "#9989A3",
        silver: "#9EA5A5",
        lightGold: "#ECD3AF",
        phthalo: "#123524",
        futarchyPurple: "#AB6BFF",
        futarchyGreen11: "#007C5C",
        futarchyGreen3: "#D7FBED",
        futarchyGreen6: "#88E5C6",
        futarchyCrimson3: "#FFE9F0",
futarchyCrimson4: "#FEDCE7",
futarchyCrimson5: "#FACEDD",
futarchyCrimson6: "#F4B3CB",
futarchyCrimson7: "#ED91B2",
futarchyCrimson9: "#E93D82",
futarchyCrimson11: "#CB1D63",
        futarchyBlue9: "#0090FF",
        futarchyBlue7: "#8EC8F6",
        futarchyBlue6: "#ACD8FC",
        futarchyBlue5: "#C2E5FF",
        futarchyBlue4: "#D5EFFF",
        futarchyBlue3: "#E6F4FE",
        futarchyBlue11: "#0D74CE",
        futarchyYellow: "#C3FF55",
        futarchyCyan: "#7EDCE4",
        futarchyLavender: "#6F78F2",
        futarchyDarkBlue: "#1A4A6B",
        futarchyBurgundy: "#70424E",
        futarchyOrange: "#F28C5A",
        futarchyGreen11: "#218358",
        futarchyGreen9: "#30A46C",
        futarchyGreen7: "#8ECEAA",
        futarchyGreen6: "#ADDDC0",
        futarchyGreen5: "#C4E8D1",
        futarchyGreen4: "#D6F1DF",
        futarchyGreen3: "#E6F6EB",
        futarchyEmerald3: "#102D24",
        futarchyEmerald32: "#D7FBED",
        futarchyEmerald6: "#1E5645",
        futarchyEmerald9: "#00CDA1",
        futarchyEmerald11: "#25D7AB",
        futarchyEmerald112: "#007C5C",
        futarchyViolet3: "#F6EDFF",
futarchyViolet4: "#EAD9FF",
futarchyViolet5: "#DCBFFF",
futarchyViolet6: "#C99DFF",
futarchyViolet7: "#B27CFA",
futarchyViolet9: "#AB6BFF",
futarchyViolet11: "#7E38CA",
        futarchyRed: "#FF6B6B",
        futarchyGray: "#8A8C8C",
        futarchyGray1: "#FCFCFC",
        futarchyGray2: "#F9F9F9",
        futarchyGray3: "#F0F0F0",
        futarchyGray4: "#E8E8E8",
        futarchyGray5: "#E1E1E1",
        futarchyGray6: "#3A3A3A",
        futarchyGray62: "#D9D9D9",
        futarchyGray10: "#7B7B7B",
        futarchyGray11: "#636363",
        futarchyGray112: "#B3B3B3",
        futarchyGray12: "#1F1F1F",
        futarchyGray122: "#EEEEEE",
        futarchyDarkGray1: "#1A1A1A",
        futarchyDarkGray2: "#191919",
        futarchyDarkGray3: "#222222",
        futarchyDarkGray4: "#191919",
        futarchyDarkGray42: "#2A2A2A",
        futarchyDarkGrayBG: "#1E1E1E",
        futarchyGrayLight: "#B8C1C8",
        futarchyGrayDark: "#4E5D6A",
        futarchyLavenderDark: "#3A3E98",
        futarchyOrange11: "#CC4E00",
        futarchyOrange9: "#F76B15",
        futarchyOrange7: "#F5AE73",
        futarchyOrange6: "#FFC182",
        futarchyOrange5: "#FFD19A",
        futarchyOrange4: "#FFDFB5",
        futarchyOrange3: "#FFEFD6",
        futarchyGold11: "#8F5C00",
        futarchyGold9: "#C48F00",
      futarchyGold8: "#DDAA00",
        futarchyGold7: "#F5C400",
        futarchyGold6: "#F8D251",
        futarchyGold5: "#FBE79F",
        futarchyGold4: "#FCEFBF",
        futarchyGold3: "#FEF7DF",

        futarchyTeal11: "#004D40",
        futarchyTeal9: "#007C6B",
        futarchyTeal7: "#00A89D",
        futarchyTeal6: "#40C4A8",
        futarchyTeal5: "#81D9C7",
        futarchyTeal4: "#A7E5DE",
        futarchyTeal3: "#D1F2EC",

        aave: {
          purple: {
            DEFAULT: "#F28C5A",
            light: "#E2A9D7",
          },
          blue: {
            DEFAULT: "#2EBAC6",
            light: "#92E9EF",
          },
          orange: {
            DEFAULT: "#FF6B3D",
            light: "#FFA981",
          },
          text: {
            primary: "#000000",
            secondary: "#6F7A9B",
          },

          dark: "#292D32",
          light: "#F1F1F3",
          gray: "#8E8E93",
        },
      },

      fontFamily: {
        oxanium: ["var(--font-oxanium)", "system-ui", "sans-serif"],
        barlow: ["var(--font-barlow)", "system-ui", "sans-serif"],
      },

      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "gradient-to-br":
          "linear-gradient(to bottom right, var(--tw-gradient-stops))", // Top-left to bottom-right
        "gradient-to-bl":
          "linear-gradient(to bottom left, var(--tw-gradient-stops))", // Top-right to bottom-left
      },
      stroke: (theme) => ({
        primary: theme("colors.primary"),
      }),
    },
  },
  plugins: [
    function ({ addUtilities }) {
      const newUtilities = {
        ".select-none": {
          userSelect: "none",
          "-webkit-user-select": "none", // Add WebKit support
        },
        ".select-text": {
          userSelect: "text",
          "-webkit-user-select": "text",
        },
        ".select-auto": {
          userSelect: "auto",
          "-webkit-user-select": "auto",
        },
        ".select-all": {
          userSelect: "all",
          "-webkit-user-select": "all",
        },
      };
      addUtilities(newUtilities, ["responsive", "hover", "focus"]);
    },
  ],
  darkMode: 'class',
};
