/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],


  theme: {
    screens: {
      zf: "864px",
      xl: "1280px",
      lg: "1024px",
      md: "768px",
      sm: "640px",
      pc: "900px",
    },
    extend: {
      keyframes: {
        "slide-down": {
          "0%": { opacity: 0, transform: "translateY(-20px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        "slide-up": {
          "0%": { opacity: 1, transform: "translateY(0)" },
          "100%": { opacity: 0, transform: "translateY(-20px)" },
        },
        "subtle-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.8" },
        },
        "ping-once": {
          "0%": { transform: "scale(1)", opacity: "1" },
          "75%, 100%": { transform: "scale(2)", opacity: "0" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: 0.1 },
          "50%": { opacity: 0.3 },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-20px)" },
        },
        "gradient-float": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        rotate: {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        pulse: {
          "0%, 100%": { transform: "scale(1)", opacity: "0.5" },
          "50%": { transform: "scale(1.1)", opacity: "0.8" },
        },
        'slide-in': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' }
        },
        'pulse-blue': {
          '0%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(0, 144, 255, 0.4)' },
          '70%': { transform: 'scale(1)', boxShadow: '0 0 0 6px rgba(0, 144, 255, 0)' },
          '100%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(0, 144, 255, 0)' }
        },
        'pulse-gold': {
          '0%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(245, 196, 0, 0.4)' },
          '70%': { transform: 'scale(1)', boxShadow: '0 0 0 6px rgba(245, 196, 0, 0)' },
          '100%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(245, 196, 0, 0)' }
        },
        'subtle-pulse': {
          '50%': {
            opacity: '.75',
          },
        },
      },
      animation: {
        "slide-down": "slide-down 0.1s ease-out forwards",
        "slide-up": "slide-up 0.1s ease-out forwards",
        "subtle-pulse": "subtle-pulse 2s ease-in-out infinite",
        "ping-once": "ping-once 1s cubic-bezier(0, 0, 0.2, 1) forwards",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "pulse-glow": "pulse-glow 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "float": "float 6s ease-in-out infinite",
        "gradient-float": "gradient-float 15s ease infinite",
        "float-slow": "float 8s ease-in-out infinite",
        "rotate-slow": "rotate 12s linear infinite",
        "pulse-slow": "pulse 6s ease-in-out infinite",
        'slide-in': 'slide-in 0.3s ease-out',
        'pulse-blue': 'pulse-blue 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-gold': 'pulse-gold 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'subtle-pulse': 'subtle-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      width: {
        22: "88px",
        87: "348px",
        90: "360px",
        100: "400px",
        120: "480px",
        143: "572px",
        220: "880px",
      },

      height: {
        12: "48px",
        87: "348px",
        100: "400px",
        107: "428px",
        133: "532px",
        142: "568px",
        147: "588px",
      },
      backdropBlur: {
        xs: '2px',
      },
      colors: {
        primary: "#45FFC5",
        lightPrimary: "#73FFD3",
        shadePrimary: "#34bf94",
        darkPrimary: "#2d9173",
        brightPrimary: "#a4ffe2",
        secondary: "#0B3F42",
        lightSecondary: "#486F71",
        darkSecondary: "#0f2d2f",
        tertiary: "#1C2322",
        dawnTertiary: "#292D2D",
        lightTertiary: "#545A59",
        darkTertiary: "#181f1e",
        black: "#141A1A",
        lightBlack: "#4E5353",
        darkBlack: "#141A1A",
        darkGray: "#31403C",
        lightDarkGray: "#414F4B",
        darkerDarkGray: "#2D3B37",
        gray: "#6D8C8E",
        lightGray: "#FAFAFA",
        darkerGray: "#425556",
        lighterGray: "#EEFFF8",
        darkLightGray: "#556465",
        danger: "#F0525C",
        lightDanger: "#F37D84",
        brightDanger: "#f7aaaf",
        darkDanger: "#86373c",
        deepDanger: "#521414",
        warning: "#E3BB42",
        lightWarning: "#EACC71",
        darkWarning: "#806e2f",
        bronze: "#DBC0A5",
        lightBronze: "#E4CFBB",
        darkBronze: "#7b7062",
        darkDarkBronze: "#554939",
        iron: "#9989A3",
        silver: "#9EA5A5",
        lightGold: "#ECD3AF",
        phthalo: "#123524",
        futarchyPurple: "#AB6BFF",
        futarchyGreen11: "#007C5C",
        futarchyGreen3: "#D7FBED",
        futarchyGreen6: "#88E5C6",
        futarchyCrimson3: "#FFE9F0",
        futarchyCrimson4: "#FEDCE7",
        futarchyCrimson5: "#FACEDD",
        futarchyCrimson6: "#F4B3CB",
        futarchyCrimson7: "#ED91B2",
        futarchyCrimson9: "#E93D82",
        futarchyCrimson10: "#CB1D63",
        futarchyCrimson11: "#CB1D63",
        futarchyBlue9: "#0090FF",
        futarchyBlue7: "#8EC8F6",
        futarchyBlue6: "#ACD8FC",
        futarchyBlue5: "#C2E5FF",
        futarchyBlue4: "#D5EFFF",
        futarchyBlue3: "#E6F4FE",
        futarchyBlue11: "#0D74CE",
        futarchyBlue10: "#0D74CE",
        futarchyYellow: "#C3FF55",
        futarchyCyan: "#7EDCE4",
        futarchyLavender: "#6F78F2",
        futarchyDarkBlue: "#1A4A6B",
        futarchyBurgundy: "#70424E",
        futarchyOrange: "#F28C5A",
        futarchyGreen11: "#218358",
        futarchyGreen9: "#30A46C",
        futarchyGreen7: "#8ECEAA",
        futarchyGreen6: "#ADDDC0",
        futarchyGreen5: "#C4E8D1",
        futarchyGreen4: "#D6F1DF",
        futarchyGreen3: "#E6F6EB",
        futarchyEmerald3: "#102D24",
        futarchyEmerald32: "#D7FBED",
        futarchyEmerald6: "#1E5645",
        futarchyEmerald9: "#00CDA1",
        futarchyEmerald11: "#25D7AB",
        futarchyEmerald112: "#007C5C",
        futarchyViolet3: "#F6EDFF",
        futarchyViolet4: "#EAD9FF",
        futarchyViolet5: "#DCBFFF",
        futarchyViolet6: "#C99DFF",
        futarchyViolet7: "#B27CFA",
        futarchyViolet9: "#AB6BFF",
        futarchyViolet10: "#7E38CA",
        futarchyViolet11: "#7E38CA",
        futarchyRed: "#FF6B6B",
        futarchyGray: "#8A8C8C",
        futarchyGray1: "#FCFCFC",
        futarchyGray2: "#F9F9F9",
        futarchyGray3: "#F0F0F0",
        futarchyGray4: "#E8E8E8",
        futarchyGray5: "#E1E1E1",
        futarchyGray6: "#3A3A3A",
        futarchyGray62: "#D9D9D9",
        futarchyGray10: "#7B7B7B",
        futarchyGray11: "#636363",
        futarchyGray112: "#B3B3B3",
        futarchyGray12: "#1F1F1F",
        futarchyGray122: "#EEEEEE",
        futarchyDarkGray1: "#1A1A1A",
        futarchyDarkGray2: "#191919",
        futarchyDarkGray3: "#222222",
        futarchyDarkGray4: "#191919",
        futarchyDarkGray42: "#2A2A2A",
        futarchyDarkGrayBG: "#1E1E1E",
        futarchyGrayLight: "#B8C1C8",
        futarchyGrayDark: "#4E5D6A",
        futarchyLavenderDark: "#3A3E98",
        futarchyOrange11: "#CC4E00",
        futarchyOrange9: "#F76B15",
        futarchyOrange7: "#F5AE73",
        futarchyOrange6: "#FFC182",
        futarchyOrange5: "#FFD19A",
        futarchyOrange4: "#FFDFB5",
        futarchyOrange3: "#FFEFD6",
        futarchyGold11: "#8F5C00",
        futarchyGold9: "#C48F00",
        futarchyGold10: "#8F5C00",
        futarchyGold8: "#DDAA00",
        futarchyGold7: "#F5C400",
        futarchyGold6: "#F8D251",
        futarchyGold5: "#FBE79F",
        futarchyGold4: "#FCEFBF",
        futarchyGold3: "#FEF7DF",

        futarchyTeal11: "#004D40",
        futarchyTeal9: "#007C6B",
        futarchyTeal10: "#004d40",
        futarchyTeal7: "#00A89D",
        futarchyTeal6: "#40C4A8",
        futarchyTeal5: "#81D9C7",
        futarchyTeal4: "#A7E5DE",
        futarchyTeal3: "#D1F2EC",

        aave: {
          purple: {
            DEFAULT: "#F28C5A",
            light: "#E2A9D7",
          },
          blue: {
            DEFAULT: "#2EBAC6",
            light: "#92E9EF",
          },
          orange: {
            DEFAULT: "#FF6B3D",
            light: "#FFA981",
          },
          text: {
            primary: "#000000",
            secondary: "#6F7A9B",
          },

          dark: "#292D32",
          light: "#F1F1F3",
          gray: "#8E8E93",
        },
      },

      fontFamily: {
        oxanium: ["var(--font-oxanium)", "system-ui", "sans-serif"],
        barlow: ["var(--font-barlow)", "system-ui", "sans-serif"],
      },

      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "gradient-to-br":
          "linear-gradient(to bottom right, var(--tw-gradient-stops))", // Top-left to bottom-right
        "gradient-to-bl":
          "linear-gradient(to bottom left, var(--tw-gradient-stops))", // Top-right to bottom-left
      },
      stroke: (theme) => ({
        primary: theme("colors.primary"),
      }),
    },
  },
  plugins: [
    function ({ addUtilities }) {
      const newUtilities = {
        ".select-none": {
          userSelect: "none",
          "-webkit-user-select": "none", // Add WebKit support
        },
        ".select-text": {
          userSelect: "text",
          "-webkit-user-select": "text",
        },
        ".select-auto": {
          userSelect: "auto",
          "-webkit-user-select": "auto",
        },
        ".select-all": {
          userSelect: "all",
          "-webkit-user-select": "all",
        },
      };
      addUtilities(newUtilities, ["responsive", "hover", "focus"]);
    },
  ],
  darkMode: 'class',
};
