
import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/widgets/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                background: "var(--background)",
                foreground: "var(--foreground)",

                // Official Futarchy Colors
                primary: "#45FFC5",
                lightPrimary: "#73FFD3",
                shadePrimary: "#34bf94",
                darkPrimary: "#2d9173",
                brightPrimary: "#a4ffe2",
                secondary: "#0B3F42",
                lightSecondary: "#486F71",
                darkSecondary: "#0f2d2f",
                tertiary: "#1C2322",
                dawnTertiary: "#292D2D",
                lightTertiary: "#545A59",
                darkTertiary: "#181f1e",
                black: "#141A1A",
                lightBlack: "#4E5353",
                darkBlack: "#141A1A",
                darkGray: "#31403C",
                lightDarkGray: "#414F4B",
                darkerDarkGray: "#2D3B37",
                gray: "#6D8C8E",
                lightGray: "#FAFAFA",
                darkerGray: "#425556",
                lighterGray: "#EEFFF8",
                darkLightGray: "#556465",
                danger: "#F0525C",
                lightDanger: "#F37D84",
                brightDanger: "#f7aaaf",
                darkDanger: "#86373c",
                deepDanger: "#521414",
                warning: "#E3BB42",
                lightWarning: "#EACC71",
                darkWarning: "#806e2f",
                bronze: "#DBC0A5",
                lightBronze: "#E4CFBB",
                darkBronze: "#7b7062",
                darkDarkBronze: "#554939",
                iron: "#9989A3",
                silver: "#9EA5A5",
                lightGold: "#ECD3AF",
                phthalo: "#123524",
                futarchyPurple: "#AB6BFF",

                // Crimsons
                futarchyCrimson3: "#FFE9F0",
                futarchyCrimson4: "#FEDCE7",
                futarchyCrimson5: "#FACEDD",
                futarchyCrimson6: "#F4B3CB",
                futarchyCrimson7: "#ED91B2",
                futarchyCrimson9: "#E93D82",
                futarchyCrimson11: "#CB1D63",

                // Blues
                futarchyBlue9: "#0090FF",
                futarchyBlue7: "#8EC8F6",
                futarchyBlue6: "#ACD8FC",
                futarchyBlue5: "#C2E5FF",
                futarchyBlue4: "#D5EFFF",
                futarchyBlue3: "#E6F4FE",
                futarchyBlue11: "#0D74CE",

                // Greens
                futarchyGreen11: "#218358",
                futarchyGreen9: "#30A46C",
                futarchyGreen7: "#8ECEAA",
                futarchyGreen6: "#ADDDC0",
                futarchyGreen5: "#C4E8D1",
                futarchyGreen4: "#D6F1DF",
                futarchyGreen3: "#E6F6EB",
                futarchyEmerald3: "#102D24",
                futarchyEmerald32: "#D7FBED",
                futarchyEmerald6: "#1E5645",
                futarchyEmerald9: "#00CDA1",
                futarchyEmerald11: "#25D7AB",
                futarchyEmerald112: "#007C5C",

                // Violets
                futarchyViolet3: "#F6EDFF",
                futarchyViolet4: "#EAD9FF",
                futarchyViolet5: "#DCBFFF",
                futarchyViolet6: "#C99DFF",
                futarchyViolet7: "#B27CFA",
                futarchyViolet9: "#AB6BFF",
                futarchyViolet11: "#7E38CA",
                futarchyRed: "#FF6B6B",

                // Grays
                futarchyGray: "#8A8C8C",
                futarchyGray1: "#FCFCFC",
                futarchyGray2: "#F9F9F9",
                futarchyGray3: "#F0F0F0",
                futarchyGray4: "#E8E8E8",
                futarchyGray5: "#E1E1E1",
                futarchyGray6: "#3A3A3A",
                futarchyGray62: "#D9D9D9",
                futarchyGray10: "#7B7B7B",
                futarchyGray11: "#636363",
                futarchyGray112: "#B3B3B3",
                futarchyGray12: "#1F1F1F",
                futarchyGray122: "#EEEEEE",
                futarchyDarkGray1: "#1A1A1A",
                futarchyDarkGray2: "#191919",
                futarchyDarkGray3: "#222222",
                futarchyDarkGray4: "#191919",
                futarchyDarkGray42: "#2A2A2A",
                futarchyDarkGrayBG: "#1E1E1E",
                futarchyGrayLight: "#B8C1C8",
                futarchyGrayDark: "#4E5D6A",
                futarchyLavenderDark: "#3A3E98",

                // Oranges & Golds
                futarchyOrange11: "#CC4E00",
                futarchyOrange9: "#F76B15",
                futarchyOrange7: "#F5AE73",
                futarchyOrange6: "#FFC182",
                futarchyOrange5: "#FFD19A",
                futarchyOrange4: "#FFDFB5",
                futarchyOrange3: "#FFEFD6",
                futarchyGold11: "#8F5C00",
                futarchyGold9: "#C48F00",
                futarchyGold8: "#DDAA00",
                futarchyGold7: "#F5C400",
                futarchyGold6: "#F8D251",
                futarchyGold5: "#FBE79F",
                futarchyGold4: "#FCEFBF",
                futarchyGold3: "#FEF7DF",

                // Teals
                futarchyTeal11: "#004D40",
                futarchyTeal9: "#007C6B",
                futarchyTeal7: "#00A89D",
                futarchyTeal6: "#40C4A8",
                futarchyTeal5: "#81D9C7",
                futarchyTeal4: "#A7E5DE",
                futarchyTeal3: "#D1F2EC",

                futarchyYellow: "#C3FF55",
                futarchyCyan: "#7EDCE4",
                futarchyLavender: "#6F78F2",
                futarchyDarkBlue: "#1A4A6B",
                futarchyBurgundy: "#70424E",
                futarchyOrange: "#F28C5A",
            },
            fontFamily: {
                oxanium: ['var(--font-oxanium)', 'sans-serif'],
            },
            animation: {
                "subtle-pulse": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
            },
        },
    },
    plugins: [],
};
export default config;
