#!/usr/bin/env node
/**
 * invariants-catalog.mjs — sister to `scripts/scenarios-catalog.mjs`.
 *
 * Reads `flows/dom-api-invariant.spec.mjs` (the cross-layer DOM↔API
 * invariant suite), extracts each `test('<title>', ...)` declaration,
 * and emits `flows/INVARIANTS.md` — a human-readable catalog of the
 * invariants this suite probes.
 *
 * Unlike the scenarios catalog (which imports each scenario module to
 * read its `default` export), this script parses the spec file
 * directly because Playwright tests are inline functions, not
 * importable values. Parsing is regex-based: matches each
 * `test('...', ...)` opening and pulls out the title string.
 *
 * Each title follows the convention:
 *   slice <id> — <bug-shape description>
 * where <id> is a short token (e.g. "4b", "4c v3a", "4m"). The
 * parser splits on the em-dash to extract <id> + description, then
 * sorts entries by id for stable output.
 *
 * Output file is committed; CI can re-run the script and diff to
 * enforce the catalog stays in sync with the spec.
 *
 * Run via:  npm --prefix auto-qa/harness run invariants:catalog
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SPEC_FILE   = join(__dirname, '..', 'flows', 'dom-api-invariant.spec.mjs');
const OUTPUT_FILE = join(__dirname, '..', 'flows', 'INVARIANTS.md');

function escapePipes(s) {
    return String(s ?? '').replace(/\|/g, '\\|');
}

const src = readFileSync(SPEC_FILE, 'utf8');

// Match `test('<title>', async ({...}) => {` declarations.
// The title may contain escaped single quotes (`\'`); accept those
// inside the string. The em-dash is U+2014.
const testRe = /test\(\s*'((?:[^'\\]|\\.)*)'\s*,/g;

const entries = [];
for (const match of src.matchAll(testRe)) {
    // Unescape \' back to ' for display.
    const title = match[1].replace(/\\'/g, "'");
    // Split on the FIRST em-dash to extract the slice id + body.
    const dash = title.indexOf(' — ');
    let id, body;
    if (dash === -1) {
        // No em-dash → treat the whole title as the body, no id.
        id   = '(unlabeled)';
        body = title;
    } else {
        const head = title.slice(0, dash).trim();
        body       = title.slice(dash + 3).trim();
        // Strip a leading "slice " prefix if present so the id
        // column displays just "4b" rather than "slice 4b".
        id = head.replace(/^slice\s+/i, '');
    }
    entries.push({ id, body });
}

if (entries.length === 0) {
    console.error(
        'invariants-catalog: no `test(...)` declarations found in',
        SPEC_FILE,
    );
    process.exit(1);
}

// Sort by id. The ids contain a numeric prefix (e.g. "4", "4b") plus
// optional version suffix (e.g. "4c v3a"). Use a natural sort that
// preserves numeric ordering before alphabetic.
function naturalCompare(a, b) {
    const re = /(\d+)|(\D+)/g;
    const aParts = a.match(re) || [];
    const bParts = b.match(re) || [];
    for (let i = 0; i < Math.max(aParts.length, bParts.length); i++) {
        const ap = aParts[i] ?? '';
        const bp = bParts[i] ?? '';
        const aNum = Number(ap);
        const bNum = Number(bp);
        if (!isNaN(aNum) && !isNaN(bNum) && ap.match(/^\d+$/) && bp.match(/^\d+$/)) {
            if (aNum !== bNum) return aNum - bNum;
        } else {
            if (ap !== bp) return ap < bp ? -1 : 1;
        }
    }
    return 0;
}
entries.sort((a, b) => naturalCompare(a.id, b.id));

// Width sizing for the markdown table.
const idColWidth = Math.max(4, ...entries.map((e) => e.id.length));

const lines = [
    '# Cross-layer DOM↔API invariants — catalog',
    '',
    '_Auto-generated by `scripts/invariants-catalog.mjs`. Do not edit by hand;',
    'run `npm run invariants:catalog` to regenerate after adding or changing an invariant._',
    '',
    `Each row corresponds to one Playwright \`test(...)\` in`,
    '`flows/dom-api-invariant.spec.mjs`. The "slice id" matches the',
    'commit-history references and the PROGRESS.md entries that introduced it.',
    '',
    `**Total invariants: ${entries.length}**`,
    '',
    `| ${'slice'.padEnd(idColWidth, ' ')} | description |`,
    `|${'-'.repeat(idColWidth + 2)}|${'-'.repeat(13)}|`,
];

for (const { id, body } of entries) {
    lines.push(`| ${id.padEnd(idColWidth, ' ')} | ${escapePipes(body)} |`);
}

lines.push('');
lines.push('## Coverage dimensions (informal)');
lines.push('');
lines.push('- **Text-level field-flow**: assert mocked data appears as DOM text');
lines.push('  (org name, counts, chain badge, prices, title fallbacks).');
lines.push('- **Network-level request body**: assert the page issues GraphQL');
lines.push('  queries containing expected fields (pool addresses, etc.).');
lines.push('- **Attribute-level rendering**: assert DOM attributes derived');
lines.push('  from API data (img `src`, anchor `href`, img `alt`).');
lines.push('');
lines.push('Refer to `interface/auto-qa/harness/PROGRESS.md` for each slice\'s');
lines.push('detailed bug-shape rationale.');
lines.push('');

writeFileSync(OUTPUT_FILE, lines.join('\n'));
console.log(`✓ Wrote ${OUTPUT_FILE} (${entries.length} invariants)`);
