#!/usr/bin/env node
/**
 * scenarios-catalog.mjs — Phase 6 slice 3.
 *
 * Discovers every `auto-qa/harness/scenarios/*.scenario.mjs`,
 * dynamically imports each one to extract its `Scenario` metadata
 * (name / bugShape / route / description), and emits
 * `scenarios/SCENARIOS.md` — a human-readable bug-shape index.
 *
 * Run via:  npm --prefix auto-qa/harness run scenarios:catalog
 *      or:  npm run auto-qa:e2e:scenarios:catalog   (from interface root)
 *
 * The output file is committed; CI can re-run the script and diff
 * to enforce the catalog stays in sync with the scenarios/ dir.
 */

import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCENARIOS_DIR = join(__dirname, '..', 'scenarios');
const OUTPUT_FILE   = join(SCENARIOS_DIR, 'SCENARIOS.md');

const REQUIRED_FIELDS = ['name', 'description', 'bugShape', 'route'];

function escapePipes(s) {
    // Markdown table cells: `|` ends the cell. Escape with `\|` so
    // bug-shape strings that legitimately contain pipes don't break
    // the table layout.
    return String(s ?? '').replace(/\|/g, '\\|');
}

const files = readdirSync(SCENARIOS_DIR)
    .filter((f) => f.endsWith('.scenario.mjs'))
    .sort();

if (files.length === 0) {
    console.error('scenarios-catalog: no *.scenario.mjs files found in', SCENARIOS_DIR);
    process.exit(1);
}

const entries = await Promise.all(
    files.map(async (file) => {
        const url = pathToFileURL(join(SCENARIOS_DIR, file)).href;
        const mod = await import(url);
        const scenario = mod.default;
        if (!scenario) {
            throw new Error(`scenarios/${file}: missing default export`);
        }
        for (const field of REQUIRED_FIELDS) {
            if (!scenario[field]) {
                throw new Error(`scenarios/${file}: missing required field "${field}"`);
            }
        }
        return { file, scenario };
    }),
);

const lines = [
    '# Captured scenarios — bug-shape index',
    '',
    '_Auto-generated by `scripts/scenarios-catalog.mjs`. Do not edit by hand;',
    'run `npm run scenarios:catalog` (or `npm run auto-qa:e2e:scenarios:catalog`',
    'from the interface root) to regenerate after adding or changing a scenario._',
    '',
    'Each row links a captured bug-shape to the scenario file that guards',
    'against it. The Phase 6 wrapper spec at `flows/scenarios.spec.mjs`',
    'auto-discovers every `*.scenario.mjs` in this directory and emits one',
    'Playwright test per row. See [ADR-002](../docs/ADR-002-scenario-format.md)',
    'for the format definition.',
    '',
    `Total scenarios: **${entries.length}**`,
    '',
    '| #  | File                               | Bug shape                                                   | Route          | Description |',
    '|----|------------------------------------|-------------------------------------------------------------|----------------|-------------|',
];

for (const { file, scenario } of entries) {
    const id = file.split('-')[0];
    lines.push(
        `| ${id} | \`${file}\` | ${escapePipes(scenario.bugShape)} | \`${scenario.route}\` | ${escapePipes(scenario.description)} |`,
    );
}

lines.push('');

writeFileSync(OUTPUT_FILE, lines.join('\n'));
console.log(`✓ Wrote ${OUTPUT_FILE} (${entries.length} scenarios)`);
