/**
 * Markets configuration with SEO metadata for each market address
 * This file is auto-generated by scripts/generate-seo.mjs
 * 
 * Last updated: 2025-11-04T21:12:21.003Z
 * Total markets: 20
 * Active markets: 7
 */

export const MARKETS_CONFIG = {
  "0x2C1e08674f3F78f8a1426a41C41B8BF546fA481a": {
    "title": "Futarchy Governance: Predict KIP-81 Impact on PNK Price",
    "description": "Shape Kleros policy—trade on KIP-81 approval’s effect on PNK using PNK & sDAI. Influence governance and profit from your foresight now!",
    "image": "/assets/kleros-market-card-81.png",
    "path": "/markets/0x2C1e08674f3F78f8a1426a41C41B8BF546fA481a",
    "openGraph": {
      "title": "Futarchy Governance: Predict KIP-81 Impact on PNK Price | Futarchy.fi",
      "description": "Shape Kleros policy—trade on KIP-81 approval’s effect on PNK using PNK & sDAI. Influence governance and profit from your foresight now!",
      "image": "/assets/kleros-market-card-81.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance: Predict KIP-81 Impact on PNK Price | Futarchy.fi",
      "description": "Shape Kleros policy—trade on KIP-81 approval’s effect on PNK using PNK & sDAI. Influence governance and profit from your foresight now!",
      "image": "/assets/kleros-market-card-81.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "arbitration",
    "isActive": true,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 10,
      "approvalStatus": "pending_review",
      "resolutionStatus": "open",
      "visibility": "private",
      "endDate": "2025-11-04T19:01:40+00:00",
      "createdAt": "2025-11-04T19:10:48.972077+00:00"
    }
  },
  "0x7e9Fc0C3d6C1619d4914556ad2dEe6051Ce68418": {
    "title": "What will be the price of GNO if its price is >= 130 sDAI?",
    "description": "Predict whether Gnosis (GNO) will trade at or above 130 sDAI (Savings xDAI) by December 28, 2025, at 11:59 PM. Join the market to forecast GNO’s long-term price movement, stake your opinion with sDAI, and see where traders think GNO is headed.",
    "image": "/assets/gnosis-sdai-130.png",
    "path": "/markets/0x7e9Fc0C3d6C1619d4914556ad2dEe6051Ce68418",
    "openGraph": {
      "title": "What will be the price of GNO if its price is >= 130 sDAI? | Futarchy.fi",
      "description": "Predict whether Gnosis (GNO) will trade at or above 130 sDAI (Savings xDAI) by December 28, 2025, at 11:59 PM. Join the market to forecast GNO’s long-term price movement, stake your opinion with sDAI, and see where traders think GNO is headed.",
      "image": "/assets/gnosis-sdai-130.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will be the price of GNO if its price is >= 130 sDAI? | Futarchy.fi",
      "description": "Predict whether Gnosis (GNO) will trade at or above 130 sDAI (Savings xDAI) by December 28, 2025, at 11:59 PM. Join the market to forecast GNO’s long-term price movement, stake your opinion with sDAI, and see where traders think GNO is headed.",
      "image": "/assets/gnosis-sdai-130.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "trading",
    "isActive": true,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "on_going",
      "resolutionStatus": "closed",
      "visibility": "private",
      "endDate": "2025-12-28T23:59:00+00:00",
      "createdAt": "2025-10-28T17:30:52.122636+00:00"
    }
  },
  "0x3f124FA6B58Ee61D1162175A578c588Db9689EF0": {
    "title": "What will the impact on GNO price be if GIP-140 is approved?",
    "description": "Auto-generated pool for futarchy governance norm prediction.",
    "image": "/assets/gnosis-proposal-1.png",
    "path": "/markets/0x3f124FA6B58Ee61D1162175A578c588Db9689EF0",
    "openGraph": {
      "title": "What will the impact on GNO price be if GIP-140 is approved? | Futarchy.fi",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "/assets/gnosis-proposal-1.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on GNO price be if GIP-140 is approved? | Futarchy.fi",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "/assets/gnosis-proposal-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2025-10-28T11:23:00+00:00",
      "createdAt": "2025-10-21T21:40:07.62192+00:00"
    }
  },
  "0x7D96A3f714782710917f6045441B39483c5Dc60a": {
    "title": "What will the impact on GNO price be if GIP-139 be approved by GnosisDAO?",
    "description": "Auto-generated pool for futarchy governance norm prediction.",
    "image": "/assets/gnosis-proposal-1.png",
    "path": "/markets/0x7D96A3f714782710917f6045441B39483c5Dc60a",
    "openGraph": {
      "title": "What will the impact on GNO price be if GIP-139 be approved by GnosisDAO? | Futarchy.fi",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "/assets/gnosis-proposal-1.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "What will the impact on GNO price be if GIP-139 be approved by GnosisDAO? | Futarchy.fi",
      "description": "Auto-generated pool for futarchy governance norm prediction.",
      "image": "/assets/gnosis-proposal-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2025-10-21T06:00:00+00:00",
      "createdAt": "2025-10-14T22:25:00.40256+00:00"
    }
  },
  "0x1F54f0312E85c5AFACe2bDF15AA2514BeFDB844F": {
    "title": "Futarchy: Predict SBUX impact if CEO exits before 2026",
    "description": "Will Starbucks CEO Brian Niccol be terminated or resign before 2026-01-01 00:00 UTC? Outcomes: 'Yes' (fired/resigned) or 'No' (still CEO). If unresolved by 2026-01-01 23:59 UTC, the outcome defaults to 'No'.\n\nTrade based on your prediction of what tokenized SBUX share price will be in each scenario, earning profits by accurately anticipating market sentiment around executive turnover.",
    "image": "/assets/starbucks-market-card-1.png",
    "path": "/markets/0x1F54f0312E85c5AFACe2bDF15AA2514BeFDB844F",
    "openGraph": {
      "title": "Futarchy: Predict SBUX impact if CEO exits before 2026 | Futarchy.fi",
      "description": "Will Starbucks CEO Brian Niccol be terminated or resign before 2026-01-01 00:00 UTC? Outcomes: 'Yes' (fired/resigned) or 'No' (still CEO). If unresolved by 2026-01-01 23:59 UTC, the outcome defaults to 'No'.\n\nTrade based on your prediction of what tokenized SBUX share price will be in each scenario, earning profits by accurately anticipating market sentiment around executive turnover.",
      "image": "/assets/starbucks-market-card-1.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy: Predict SBUX impact if CEO exits before 2026 | Futarchy.fi",
      "description": "Will Starbucks CEO Brian Niccol be terminated or resign before 2026-01-01 00:00 UTC? Outcomes: 'Yes' (fired/resigned) or 'No' (still CEO). If unresolved by 2026-01-01 23:59 UTC, the outcome defaults to 'No'.\n\nTrade based on your prediction of what tokenized SBUX share price will be in each scenario, earning profits by accurately anticipating market sentiment around executive turnover.",
      "image": "/assets/starbucks-market-card-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain"
    ],
    "category": "governance",
    "isActive": true,
    "metadata": {
      "tokens": "0",
      "companyId": 12,
      "approvalStatus": "pending_review",
      "resolutionStatus": "closed",
      "visibility": "private",
      "endDate": null,
      "createdAt": "2025-10-13T20:01:56.614539+00:00"
    }
  },
  "0x2A4b52B47625431Fdc6fE58CeD3086E76c1f6bbf": {
    "title": "Futarchy: Predict TSLA impact if 2025 CEO Award passes",
    "description": "Will Tesla shareholders approve Elon Musk’s 2025 CEO Performance Award (the 'Mega Package') at the Annual Meeting on November 6, 2025? Outcomes: 'Yes' (approved) or 'No' (rejected). If unresolved by 2025-11-30 23:59 UTC, the outcome defaults to 'No'.\n\nTrade based on your prediction of what tokenized TSLA share price will be in each scenario, earning profits by accurately anticipating market sentiment regarding shareholder decisions.",
    "image": "/assets/tesla-market-card-1.png",
    "path": "/markets/0x2A4b52B47625431Fdc6fE58CeD3086E76c1f6bbf",
    "openGraph": {
      "title": "Futarchy: Predict TSLA impact if 2025 CEO Award passes | Futarchy.fi",
      "description": "Will Tesla shareholders approve Elon Musk’s 2025 CEO Performance Award (the 'Mega Package') at the Annual Meeting on November 6, 2025? Outcomes: 'Yes' (approved) or 'No' (rejected). If unresolved by 2025-11-30 23:59 UTC, the outcome defaults to 'No'.\n\nTrade based on your prediction of what tokenized TSLA share price will be in each scenario, earning profits by accurately anticipating market sentiment regarding shareholder decisions.",
      "image": "/assets/tesla-market-card-1.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy: Predict TSLA impact if 2025 CEO Award passes | Futarchy.fi",
      "description": "Will Tesla shareholders approve Elon Musk’s 2025 CEO Performance Award (the 'Mega Package') at the Annual Meeting on November 6, 2025? Outcomes: 'Yes' (approved) or 'No' (rejected). If unresolved by 2025-11-30 23:59 UTC, the outcome defaults to 'No'.\n\nTrade based on your prediction of what tokenized TSLA share price will be in each scenario, earning profits by accurately anticipating market sentiment regarding shareholder decisions.",
      "image": "/assets/tesla-market-card-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain"
    ],
    "category": "governance",
    "isActive": true,
    "metadata": {
      "tokens": "TSLAON, USDS",
      "companyId": 11,
      "approvalStatus": "on_going",
      "resolutionStatus": "closed",
      "visibility": "private",
      "endDate": "2025-11-30T00:00:00+00:00",
      "createdAt": "2025-09-23T22:08:49.873764+00:00"
    }
  },
  "0xa80641Bf70483A3524713A396deE0ebD642CEaEA": {
    "title": "Futarchy Governance Prediction: GIP-133 Approval Impact",
    "description": "Predict GnosisDAO's GIP-133 outcome and its effect on GNO price. Trade with GNO, sDAI, and influence governance—shape the future of GnosisDAO now!",
    "image": "/assets/gnosis-market-card-133.png",
    "path": "/markets/0xa80641Bf70483A3524713A396deE0ebD642CEaEA",
    "openGraph": {
      "title": "Futarchy Governance Prediction: GIP-133 Approval Impact | Futarchy.fi",
      "description": "Predict GnosisDAO's GIP-133 outcome and its effect on GNO price. Trade with GNO, sDAI, and influence governance—shape the future of GnosisDAO now!",
      "image": "/assets/gnosis-market-card-133.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: GIP-133 Approval Impact | Futarchy.fi",
      "description": "Predict GnosisDAO's GIP-133 outcome and its effect on GNO price. Trade with GNO, sDAI, and influence governance—shape the future of GnosisDAO now!",
      "image": "/assets/gnosis-market-card-133.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2025-08-21T17:47:45+00:00",
      "createdAt": "2025-08-21T18:15:37.091354+00:00"
    }
  },
  "0x0842961509da168bab5f02e81ad81230c930d48a": {
    "title": "Futarchy Governance Prediction: GIP-133 Approval Impact",
    "description": "Test",
    "image": "/assets/gnosis-market-card-133.png",
    "path": "/markets/0x0842961509da168bab5f02e81ad81230c930d48a",
    "openGraph": {
      "title": "Futarchy Governance Prediction: GIP-133 Approval Impact | Futarchy.fi",
      "description": "Test",
      "image": "/assets/gnosis-market-card-133.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: GIP-133 Approval Impact | Futarchy.fi",
      "description": "Test",
      "image": "/assets/gnosis-market-card-133.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "trading",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "closed",
      "visibility": "test",
      "endDate": "2025-12-31T00:00:00+00:00",
      "createdAt": "2025-08-18T20:58:10.373428+00:00"
    }
  },
  "0x7dbEC3FfB25c8c0fEcB3fCd4613EffC7f72008aC": {
    "title": "Futarchy Governance: Predict KIP-78 Impact on PNK Price",
    "description": "Shape Kleros policy—trade on KIP-78 approval’s effect on PNK using PNK & sDAI. Influence governance and profit from your foresight now!",
    "image": "/assets/kleros-market-card-78.png",
    "path": "/markets/0x7dbEC3FfB25c8c0fEcB3fCd4613EffC7f72008aC",
    "openGraph": {
      "title": "Futarchy Governance: Predict KIP-78 Impact on PNK Price | Futarchy.fi",
      "description": "Shape Kleros policy—trade on KIP-78 approval’s effect on PNK using PNK & sDAI. Influence governance and profit from your foresight now!",
      "image": "/assets/kleros-market-card-78.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance: Predict KIP-78 Impact on PNK Price | Futarchy.fi",
      "description": "Shape Kleros policy—trade on KIP-78 approval’s effect on PNK using PNK & sDAI. Influence governance and profit from your foresight now!",
      "image": "/assets/kleros-market-card-78.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "arbitration",
    "isActive": false,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 10,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2025-08-15T17:20:52+00:00",
      "createdAt": "2025-08-15T18:33:09.781363+00:00"
    }
  },
  "0xA94aB35282118f38b0b4FF89dDA7A5c04aD49371": {
    "title": "Futarchy Governance: Predict KIP-77 Outcome & PNK Impact",
    "description": "Shape Kleros policy—forecast KIP-77 approval and its effect on PNK price using PNK & sDAI. Join the futarchy governance market now!",
    "image": "/assets/kleros-market-card-1-bg.png",
    "path": "/markets/0xA94aB35282118f38b0b4FF89dDA7A5c04aD49371",
    "openGraph": {
      "title": "Futarchy Governance: Predict KIP-77 Outcome & PNK Impact | Futarchy.fi",
      "description": "Shape Kleros policy—forecast KIP-77 approval and its effect on PNK price using PNK & sDAI. Join the futarchy governance market now!",
      "image": "/assets/kleros-market-card-1-bg.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance: Predict KIP-77 Outcome & PNK Impact | Futarchy.fi",
      "description": "Shape Kleros policy—forecast KIP-77 approval and its effect on PNK price using PNK & sDAI. Join the futarchy governance market now!",
      "image": "/assets/kleros-market-card-1-bg.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "arbitration",
    "isActive": false,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 10,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "public",
      "endDate": "2025-07-16T19:57:54+00:00",
      "createdAt": "2025-07-29T20:38:30.621088+00:00"
    }
  },
  "0xBFE2b1B3746e401081C2abb56913c2d7042FA94d": {
    "title": "Futarchy Governance Market: GIP-128 Approval Prediction",
    "description": "Predict GIP-128's approval by GnosisDAO and its impact on GNO price using GNO & sDAI. Shape governance outcomes—trade and influence now!",
    "image": "/assets/gnosis-market-card-1-bg.png",
    "path": "/markets/0xBFE2b1B3746e401081C2abb56913c2d7042FA94d",
    "openGraph": {
      "title": "Futarchy Governance Market: GIP-128 Approval Prediction | Futarchy.fi",
      "description": "Predict GIP-128's approval by GnosisDAO and its impact on GNO price using GNO & sDAI. Shape governance outcomes—trade and influence now!",
      "image": "/assets/gnosis-market-card-1-bg.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Market: GIP-128 Approval Prediction | Futarchy.fi",
      "description": "Predict GIP-128's approval by GnosisDAO and its impact on GNO price using GNO & sDAI. Shape governance outcomes—trade and influence now!",
      "image": "/assets/gnosis-market-card-1-bg.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "resolved",
      "visibility": "private",
      "endDate": "2025-07-16T19:56:14+00:00",
      "createdAt": "2025-07-16T20:32:35.447294+00:00"
    }
  },
  "0x5acae07AA3Cffe25b3fBef3732f8E313BBbD5115": {
    "title": "Futarchy Governance Prediction: GIP-128 GnosisDAO $30M Funding Vote",
    "description": "Predict if GnosisDAO approves $30M/year for Gnosis Ltd. Trade with GNO & sDAI, shape policy, and influence GNO price through Futarchy governance now!",
    "image": "/assets/gnosis-market-card-1-bg.png",
    "path": "/markets/0x5acae07AA3Cffe25b3fBef3732f8E313BBbD5115",
    "openGraph": {
      "title": "Futarchy Governance Prediction: GIP-128 GnosisDAO $30M Funding Vote | Futarchy.fi",
      "description": "Predict if GnosisDAO approves $30M/year for Gnosis Ltd. Trade with GNO & sDAI, shape policy, and influence GNO price through Futarchy governance now!",
      "image": "/assets/gnosis-market-card-1-bg.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: GIP-128 GnosisDAO $30M Funding Vote | Futarchy.fi",
      "description": "Predict if GnosisDAO approves $30M/year for Gnosis Ltd. Trade with GNO & sDAI, shape policy, and influence GNO price through Futarchy governance now!",
      "image": "/assets/gnosis-market-card-1-bg.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": true,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "open",
      "visibility": "private",
      "endDate": "2025-07-16T19:56:14+00:00",
      "createdAt": "2025-07-16T19:50:48.368972+00:00"
    }
  },
  "0xC5A3Ff432233cceab9b40a568966FcaD54a24BeB": {
    "title": "Futarchy Governance Prediction: GIP-128 GNO Funding Vote",
    "description": "Predict GIP-128’s approval and its effect on GNO price using GNO & sDAI. Shape GnosisDAO policy—trade or participate in this key governance market!",
    "image": "/assets/gnosis-proposal-1.png",
    "path": "/markets/0xC5A3Ff432233cceab9b40a568966FcaD54a24BeB",
    "openGraph": {
      "title": "Futarchy Governance Prediction: GIP-128 GNO Funding Vote | Futarchy.fi",
      "description": "Predict GIP-128’s approval and its effect on GNO price using GNO & sDAI. Shape GnosisDAO policy—trade or participate in this key governance market!",
      "image": "/assets/gnosis-proposal-1.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: GIP-128 GNO Funding Vote | Futarchy.fi",
      "description": "Predict GIP-128’s approval and its effect on GNO price using GNO & sDAI. Shape GnosisDAO policy—trade or participate in this key governance market!",
      "image": "/assets/gnosis-proposal-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "open",
      "visibility": "test",
      "endDate": "2025-07-16T02:12:28+00:00",
      "createdAt": "2025-07-16T04:34:32.191909+00:00"
    }
  },
  "0xec50a351C0A4A122DC614058C0481Bb9487Abdaa": {
    "title": "Futarchy Governance Prediction: KIP-76 PNK Minting Approval?",
    "description": "Predict KIP-76’s impact on PNK price using sDAI and PNK in this futarchy governance market. Influence Kleros policy—trade or participate now!",
    "image": "/assets/kleros-market-card-2-bg.png",
    "path": "/markets/0xec50a351C0A4A122DC614058C0481Bb9487Abdaa",
    "openGraph": {
      "title": "Futarchy Governance Prediction: KIP-76 PNK Minting Approval? | Futarchy.fi",
      "description": "Predict KIP-76’s impact on PNK price using sDAI and PNK in this futarchy governance market. Influence Kleros policy—trade or participate now!",
      "image": "/assets/kleros-market-card-2-bg.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: KIP-76 PNK Minting Approval? | Futarchy.fi",
      "description": "Predict KIP-76’s impact on PNK price using sDAI and PNK in this futarchy governance market. Influence Kleros policy—trade or participate now!",
      "image": "/assets/kleros-market-card-2-bg.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 10,
      "approvalStatus": "on_going",
      "resolutionStatus": "resolved",
      "visibility": "public",
      "endDate": "2025-07-15T23:59:59+00:00",
      "createdAt": "2025-06-30T01:21:31.393888+00:00"
    }
  },
  "0xf36e2f05E8F45954d896b2ed72cD2a0bAB6A6Dd7": {
    "title": "Futarchy Governance Market: KIP-76 Approval & PNK Price Impact",
    "description": "Predict KIP-76 approval before July 16, 2025. Stake PNK or sDAI to influence governance and forecast PNK price outcomes. Join and shape policy now!",
    "image": "/assets/kleros-proposal-1.png",
    "path": "/markets/0xf36e2f05E8F45954d896b2ed72cD2a0bAB6A6Dd7",
    "openGraph": {
      "title": "Futarchy Governance Market: KIP-76 Approval & PNK Price Impact | Futarchy.fi",
      "description": "Predict KIP-76 approval before July 16, 2025. Stake PNK or sDAI to influence governance and forecast PNK price outcomes. Join and shape policy now!",
      "image": "/assets/kleros-proposal-1.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Market: KIP-76 Approval & PNK Price Impact | Futarchy.fi",
      "description": "Predict KIP-76 approval before July 16, 2025. Stake PNK or sDAI to influence governance and forecast PNK price outcomes. Join and shape policy now!",
      "image": "/assets/kleros-proposal-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "open",
      "visibility": "test",
      "endDate": "2025-07-16T23:59:59+00:00",
      "createdAt": "2025-06-30T01:10:58.33154+00:00"
    }
  },
  "0xa6A71F5335447B1e711ab9c78c52a24BE6c9f997": {
    "title": "Futarchy Governance Prediction: KIP-76 Approval & PNK Impact",
    "description": "Predict KIP-76's approval for PNK minting by 2026. Trade with PNK & sDAI, shape governance, and influence DeFi policy outcomes now!",
    "image": "/assets/kleros-proposal-1.png",
    "path": "/markets/0xa6A71F5335447B1e711ab9c78c52a24BE6c9f997",
    "openGraph": {
      "title": "Futarchy Governance Prediction: KIP-76 Approval & PNK Impact | Futarchy.fi",
      "description": "Predict KIP-76's approval for PNK minting by 2026. Trade with PNK & sDAI, shape governance, and influence DeFi policy outcomes now!",
      "image": "/assets/kleros-proposal-1.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: KIP-76 Approval & PNK Impact | Futarchy.fi",
      "description": "Predict KIP-76's approval for PNK minting by 2026. Trade with PNK & sDAI, shape governance, and influence DeFi policy outcomes now!",
      "image": "/assets/kleros-proposal-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "PNK",
      "Kleros",
      "arbitration",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": false,
    "metadata": {
      "tokens": "PNK, sDAI",
      "companyId": 10,
      "approvalStatus": "pending_review",
      "resolutionStatus": "closed",
      "visibility": "test",
      "endDate": "2025-12-31T23:59:59+00:00",
      "createdAt": "2025-06-29T04:28:09.981958+00:00"
    }
  },
  "0x3e2176000a869FDDD5A4D58A66513fa834955570": {
    "title": "Futarchy Governance: Predict Gnosis TVL & Policy Impact",
    "description": "Shape Gnosis policy via Futarchy! Trade GNO & sDAI to decide if $400M TVL boosts GNO price. Influence DeFi governance—join the market now.",
    "image": "/assets/gnosis-proposal-1.png",
    "path": "/markets/0x3e2176000a869FDDD5A4D58A66513fa834955570",
    "openGraph": {
      "title": "Futarchy Governance: Predict Gnosis TVL & Policy Impact | Futarchy.fi",
      "description": "Shape Gnosis policy via Futarchy! Trade GNO & sDAI to decide if $400M TVL boosts GNO price. Influence DeFi governance—join the market now.",
      "image": "/assets/gnosis-proposal-1.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance: Predict Gnosis TVL & Policy Impact | Futarchy.fi",
      "description": "Shape Gnosis policy via Futarchy! Trade GNO & sDAI to decide if $400M TVL boosts GNO price. Influence DeFi governance—join the market now.",
      "image": "/assets/gnosis-proposal-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "defi",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "closed",
      "visibility": "test",
      "endDate": "2025-12-31T00:00:00+00:00",
      "createdAt": "2025-06-23T19:58:37.668206+00:00"
    }
  },
  "0x757fAF022abf920E110d6C4DbC2477A99788F447": {
    "title": "Futarchy Governance Prediction: GnosisDAO $5M Policy Market",
    "description": "Predict if GnosisDAO will adopt futarchy for $5M+ decisions using GNO & sDAI. Influence future governance—trade now to shape DAO policy outcomes!",
    "image": "/assets/gnosis-market-card-6-bg.png",
    "path": "/markets/0x757fAF022abf920E110d6C4DbC2477A99788F447",
    "openGraph": {
      "title": "Futarchy Governance Prediction: GnosisDAO $5M Policy Market | Futarchy.fi",
      "description": "Predict if GnosisDAO will adopt futarchy for $5M+ decisions using GNO & sDAI. Influence future governance—trade now to shape DAO policy outcomes!",
      "image": "/assets/gnosis-market-card-6-bg.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Prediction: GnosisDAO $5M Policy Market | Futarchy.fi",
      "description": "Predict if GnosisDAO will adopt futarchy for $5M+ decisions using GNO & sDAI. Influence future governance—trade now to shape DAO policy outcomes!",
      "image": "/assets/gnosis-market-card-6-bg.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": true,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "on_going",
      "resolutionStatus": "closed",
      "visibility": "public",
      "endDate": "2025-12-31T00:00:00+00:00",
      "createdAt": "2025-06-20T19:27:26.183123+00:00"
    }
  },
  "0x9590dAF4d5cd4009c3F9767C5E7668175cFd37CF": {
    "title": "Futarchy Governance: Predict USDC Deployment on Gnosis Chain",
    "description": "Shape Gnosis Chain policy: Vote with GNO & sDAI on Circle’s USDC deployment and its impact on GNO price. Influence decisions—trade or govern now!",
    "image": "/assets/gnosis-market-card-7-bg.png",
    "path": "/markets/0x9590dAF4d5cd4009c3F9767C5E7668175cFd37CF",
    "openGraph": {
      "title": "Futarchy Governance: Predict USDC Deployment on Gnosis Chain | Futarchy.fi",
      "description": "Shape Gnosis Chain policy: Vote with GNO & sDAI on Circle’s USDC deployment and its impact on GNO price. Influence decisions—trade or govern now!",
      "image": "/assets/gnosis-market-card-7-bg.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance: Predict USDC Deployment on Gnosis Chain | Futarchy.fi",
      "description": "Shape Gnosis Chain policy: Vote with GNO & sDAI on Circle’s USDC deployment and its impact on GNO price. Influence decisions—trade or govern now!",
      "image": "/assets/gnosis-market-card-7-bg.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "governance",
    "isActive": true,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "on_going",
      "resolutionStatus": "closed",
      "visibility": "public",
      "endDate": "2025-12-31T23:59:59+00:00",
      "createdAt": "2025-06-16T22:24:01.956427+00:00"
    }
  },
  "0xDA36a35CA4Fe6214C37a452159C0C9EAd45D5919": {
    "title": "Futarchy Governance Market: GnosisPay €2M Volume & GNO Impact",
    "description": "Trade GNO or sDAI in this Futarchy market to influence GnosisPay policy. Decide if €2M weekly volume will affect GNO price. Shape governance now!",
    "image": "/assets/gnosis-proposal-1.png",
    "path": "/markets/0xDA36a35CA4Fe6214C37a452159C0C9EAd45D5919",
    "openGraph": {
      "title": "Futarchy Governance Market: GnosisPay €2M Volume & GNO Impact | Futarchy.fi",
      "description": "Trade GNO or sDAI in this Futarchy market to influence GnosisPay policy. Decide if €2M weekly volume will affect GNO price. Shape governance now!",
      "image": "/assets/gnosis-proposal-1.png",
      "type": "website",
      "siteName": "Futarchy.fi"
    },
    "twitter": {
      "card": "summary_large_image",
      "title": "Futarchy Governance Market: GnosisPay €2M Volume & GNO Impact | Futarchy.fi",
      "description": "Trade GNO or sDAI in this Futarchy market to influence GnosisPay policy. Decide if €2M weekly volume will affect GNO price. Shape governance now!",
      "image": "/assets/gnosis-proposal-1.png"
    },
    "keywords": [
      "futarchy",
      "prediction market",
      "governance",
      "blockchain",
      "GNO",
      "Gnosis",
      "GnosisDAO",
      "sDAI",
      "savings",
      "DeFi",
      "expansao",
      "global",
      "estrategia"
    ],
    "category": "trading",
    "isActive": false,
    "metadata": {
      "tokens": "GNO, sDAI",
      "companyId": 9,
      "approvalStatus": "pending_review",
      "resolutionStatus": "resolved",
      "visibility": "public",
      "endDate": "2025-07-01T02:59:00+00:00",
      "createdAt": "2025-05-26T22:17:47.210777+00:00"
    }
  }
};

/**
 * Get all market addresses that should be statically generated
 */
export function getStaticMarketAddresses() {
  return Object.keys(MARKETS_CONFIG);
}

/**
 * Get market configuration by address
 */
export function getMarketConfig(address) {
  return MARKETS_CONFIG[address] || null;
}

/**
 * Get all active market configurations
 */
export function getAllActiveMarkets() {
  return Object.entries(MARKETS_CONFIG)
    .filter(([_, config]) => config.isActive)
    .map(([address, config]) => ({ address, ...config }));
}

/**
 * Generate dynamic SEO metadata for a market
 */
export function generateMarketSEO(address, marketData = null) {
  const config = getMarketConfig(address);
  if (!config) return null;

  // Allow dynamic override from marketData if available
  const title = marketData?.seoTitle || config.title;
  const description = marketData?.seoDescription || config.description;
  const image = marketData?.seoImage || config.image;

  return {
    title: `${title} | Futarchy.fi`,
    description,
    image,
    url: `https://app.futarchy.fi${config.path}`,
    openGraph: {
      ...config.openGraph,
      title: marketData?.seoTitle ? `${marketData.seoTitle} | Futarchy.fi` : config.openGraph.title,
      description: marketData?.seoDescription || config.openGraph.description,
      image: marketData?.seoImage || config.openGraph.image,
      url: `https://app.futarchy.fi${config.path}`
    },
    twitter: {
      ...config.twitter,
      title: marketData?.seoTitle ? `${marketData.seoTitle} | Futarchy.fi` : config.twitter.title,
      description: marketData?.seoDescription || config.twitter.description,
      image: marketData?.seoImage || config.twitter.image
    }
  };
}